#!/usr/bin/env python
import os, sys, glob, time, datetime
from stat import ST_MTIME

#fn=glob.glob('*.dmg')+glob.glob('*.zip')
fn=sorted(glob.glob('*.dmg')+glob.glob('*.zip'),key=str.lower)
fnshort=[f[0:-4] for f in fn]
k=len(fnshort)
fntext=['']*k
fndate=['']*k
for i in range(k):
	fndate[i]=repr(time.strftime("%Y-%m-%d %H:%M",time.localtime(os.stat(fn[i])[ST_MTIME])))[1:-1]
	#print fndate[0], fndate[0][1:-1]

	try:
		with open(fnshort[i]+'.txt','r') as g:
			fntext[i]=g.read().strip()
	except IOError:
		pass

today=datetime.datetime.today()			
pagehead='''<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO8859-I" />
<link type="css/text" rel="stylesheet" href="myindex.css" />
<title>HSchulz TeX files</title></head>
<body>
<h1>TeX Software by Herb Schulz</h1>
'''
tablestart='''<table>
<caption><Large><strong>Downloads</strong></Large></caption>
<tr><th>File</th><th>Modified</th><th>Description</th></tr>
'''
pagefoot='</body></html>\n'
with open('../index.html','w') as f:
	f.write(pagehead)
	f.write(tablestart)
	for i in range(k):
		f.write('<tr><td><a href="Files/'+fn[i]+'">'+fn[i]+'</a></td><td>'+fndate[i]+'</td><td>'+fntext[i]+'</td></tr>\n')
	f.write('</table> <br> Last updated: '+str(today)[0:-10])

exit(0)